pre-commit fails if make test fails. fixing factorial's style

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,5 +1,9 @@
 pwd
 make test
+if [ $? -ne 0 ]; then
+  echo "Some of your tests failed."
+  exit 1
+fi
 if [ `date +%w` -eq 6 ]; then
   echo "Enjoy your life. Do not code on Sunday!"
 fi
